ScrimbaBootcamp/progress-tracker

README.md
This checklist will have corresponding issues so that contributors may expand on this README file.
=> Added checklist of info to include in README

CONTRIBUTING.md, README.md
I created the CONTRIBUTING file, and outlined steps to get started in the terminal. I left code comments for sections to be filled in. Open to input - do we want to lay out the git workflow three different ways? It could be a good beginner issue to add this documentation. If giving three sets of instructions, a Table of Contents would be helpful.
=> Getting started with terminal

CONTRIBUTING.md
I created the CONTRIBUTING file, and outlined steps to get started in the terminal. I left code comments for sections to be filled in. Open to input - do we want to lay out the git workflow three different ways? It could be a good beginner issue to add this documentation. If giving three sets of instructions, a Table of Contents would be helpful.
=> Getting started with git, formatting fixes

CONTRIBUTING.md
Deleted remote branch too soon and changes weren't reflected.
=> Line breaks

CONTRIBUTING.md
In CONTRIBUTING.md, I added steps to create (and also delete) a feature branch from the terminal.
=> Added steps to create a feature branch

contributors.js
This will be a JSON file where contributors can add their name, social links, and avatar. Will later be rendered in `contributors.html`.
=> Created contributors.js, and added my info

CONTRIBUTING.md
Added to CONTRIBUTING.md, with steps for staging, committing and pushing changes made in a local branch up to a remote branch.
=> steps to add, commit, and push with git commands

CONTRIBUTING.md
I had used the wrong character '/' to escape to a new line. Changed these characters to `\`, for better formatting.
=> Changed characters for new line

contributors.js
Moved `curriculum.html`, `activities.html` and `contributors.html` to `html` folder for better organization.
=> Added folder for HTML files other than index.

CONTRIBUTING.md
Added steps to create a pull request across forks. Still need to add a step and screenshots.
=> Added steps to submit a pull request

CONTRIBUTING.md
Added step for someone to compare across forks. Edited name of the head repository one should be looking for.
=> Added step and made edit to name of head repo

CONTRIBUTING.md
Changed productivity-app to progress-tracker.
=> Fixed link names

CONTRIBUTING.md
Added guidelines before the 'Getting Started' section, to indicate that contributors should request assignment to an Issue before making changes and submitting pull requests.
=> Added general guidelines for contributing.

CONTRIBUTING.md
Added to Contributing, with steps for syncing a fork. Added placeholder for how to resolve merge conflicts.
=> Added steps for syncing a fork

index.html
We don't have any code that is being rendered on the page. Added an `h1` just for a sanity check.
=> Added text to appear on home page

html/htmlNotes.html
Adding content to the site. Using one of Rae's pages from their Notes app.
=> Added a file from Rae's repo

html/activities.html, html/contributors.html, html/curriculum.html, html/htmlNotes.html, index.html
I added the link the link tag to the html files. 
I think it impacted activities.html, contributors.html and curriculum.html. The boilerplate code for htmlNotes needs to be reviewed and worked on. I felt that was outside the scope of the issue assigned to me.
=> Addedcsslinktohtmlfiles

README.md
testing something to help student
=> added url in comment

index.css
Hi :), I added all the colors to the css  from the figma file. The root and added those variables in the rest of the app.
=> added the root colors and add them to our styles

index.css, index.html
1. Add : Font Awesome
2. Change : Hover Effect from background to bottom border with animation
=> refactor nav / add animation in hover / focus / active

CONTRIBUTING.md
Re-organized the Contributing Guidelines to keep all VS Code instruction in one section and all terminal instruction in another. Also re-sized images in hopes of improving readabiity.
=> Contributing fixes

index.html
I made a new section and added it in the html
=> added new section

html/curriculum.html
Fixed the spelling error on line 51
=> Spelling Correction

html/contributors.html, html/curriculum.html
quick fix for issue 78
it was fixed a few weeks ago finally got the change pushed up
=> fixed issue

html/contributors.html, html/curriculum.html
quick fix to file paths in the navigation bar in contributors.html and curriculum.html as well. The last file paths were broken, now we go up a level in the directory to access index.html.
=> Nav bar updated to use the same as index.html, file paths fixed

html/accessibilityNotes.html, html/codeReviewNotes.html, html/cssNotes.html, html/firebaseNotes.html, html/htmlNotes.html, html/javascriptNotes.html
HTML notes, CSS notes, JavaScript notes, Firebase notes, Accessibility notes, and Code Review notes
=> created files for notes I have taken through scrimba

index.css
added hover effect on links, they will change color and background color, added transition as well"
=> Added hover effect on nav links
